name: Build & Publish to PyPI

on:
  push:
    tags:
      - "v*"         # e.g. v0.1.0
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build dists
    runs-on: ubuntu-latest
    env:
      # If your tests import config from env, feel free to tweak/remove
      HRMS_API_BASE_URL: "https://example.com/api"
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install build & test deps
        run: |
          python -m pip install --upgrade pip
          pip install build pytest

      - name: Run tests
        run: pytest -q

      - name: Build sdist & wheel
        run: python -m build

      - name: Upload dist artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/*

  publish:
    name: Publish to PyPI
    needs: build
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write   # required for Trusted Publishing (OIDC)
      contents: read
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
